version: '3.5'
services:
  milvus-minio:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
  milvus:
    image: milvusdb/milvus:v2.4.6
    command: milvus run standalone
    environment:
      ETCD_USE_EMBED: "true"
      PULSAR_USE_EMBED: "true"
      MINIO_ADDRESS: "milvus-minio:9000"
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadmin"
      MINIO_USE_SSL: "false"
    depends_on:
      - milvus-minio
    ports:
      - "19530:19530"
      - "9091:9091"